# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdea1901cc0dcb87ebdfa4edcf3543fa3da4f3008fc102855fc85a2837b57626a0be62ba9f0bed1552eab8b38ba794348a145b821681b2b9ada8e30b14dd7a37

test:
  secret_key_base: 01cd81cc3fb79ab064a0a4f6636eeee5b2d001653ed455146dc4cc605b21927cb8e832dad23f0d5152247656e5704a2f55062d24e214f9fab80b22fed81cf7fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
